<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class DenominacionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $denominacion=[
            // pregrado bachiller
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'101'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'102'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'103'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'104'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'105'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'106'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'107'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'108'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'109'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'110'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'111'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'112'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'113'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'114'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'115'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'116'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'117'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'118'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'119'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'120'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'121'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'122'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'123'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'124'],
            ['nombre'=>'BACHILLER EN: DERECHO','grado_id'=>'1','id'=>'125'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'126'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'127'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'128'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'129'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'130'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'131'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'132'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'133'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'134'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'135'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'136'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'137'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'138'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'139'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'140'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'141'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'142'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'143'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'144'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'145'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'146'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'147'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'148'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'149'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'150'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'151'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'152'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'153'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'154'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'155'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'156'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'157'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'158'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'159'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'160'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'161'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'162'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'163'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'164'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'165'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'166'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'1','id'=>'167'],
            ['nombre'=>'BACHILLER EN: MEDICINA HUMANA','grado_id'=>'1','id'=>'200'],
            ['nombre'=>'BACHILLER EN: CIENCIAS INGENIERÍA AMBIENTAL','grado_id'=>'1','id'=>'300'],
            ['nombre'=>'BACHILLER EN: CIENCIAS INGENIERÍA AMBIENTAL','grado_id'=>'1','id'=>'302'],
            ['nombre'=>'BACHILLER EN: CIENCIAS INGENIERÍA CIVIL','grado_id'=>'1','id'=>'303'],
            ['nombre'=>'BACHILLER EN: CIENCIAS INGENIERÍA GEOLÓGICA','grado_id'=>'1','id'=>'304'],
            ['nombre'=>'BACHILLER EN: CIENCIAS INGENIERÍA METALÚRGICA','grado_id'=>'1','id'=>'305'],
            ['nombre'=>'BACHILLER EN: CIENCIAS INGENERIA DE MINAS','grado_id'=>'1','id'=>'306'],
            ['nombre'=>'BACHILLER EN: CIENCIAS INGENIERÍA DE SISTEMAS Y COMPUTACIÓN','grado_id'=>'1','id'=>'307'],
            ['nombre'=>'BACHILLER EN: CIENCIAS INGENIERÍA DE SISTEMAS Y COMPUTACIÓN','grado_id'=>'1','id'=>'308'],
            ['nombre'=>'BACHILLER EN: ODONTOLOGÍA','grado_id'=>'1','id'=>'400'],
            ['nombre'=>'BACHILLER EN: CIENCIAS AGRONOMÍA','grado_id'=>'1','id'=>'500'],
            ['nombre'=>'BACHILLER EN: CIENCIAS AGRONOMÍA','grado_id'=>'1','id'=>'502'],
            ['nombre'=>'BACHILLER EN: CIENCIAS AGRONOMÍA','grado_id'=>'1','id'=>'503'],
            ['nombre'=>'BACHILLER EN: CIENCIAS AGRONOMÍA','grado_id'=>'1','id'=>'504'],
            ['nombre'=>'BACHILLER EN: CIENCIAS AGRONOMÍA','grado_id'=>'1','id'=>'505'],
            ['nombre'=>'BACHILLER EN: CIENCIAS AGRONOMÍA','grado_id'=>'1','id'=>'506'],
            ['nombre'=>'BACHILLER EN: CIENCIAS AGRONOMÍA','grado_id'=>'1','id'=>'507'],
            ['nombre'=>'BACHILLER EN:CIENCIAS INDUSTRIAS ALIMENTARIAS','grado_id'=>'1','id'=>'508'],
            ['nombre'=>'BACHILLER EN:CIENCIAS INDUSTRIAS ALIMENTARIAS','grado_id'=>'1','id'=>'509'],
            ['nombre'=>'BACHILLER EN: CIENCIAS ZOOTECNIA','grado_id'=>'1','id'=>'510'],
            ['nombre'=>'BACHILLER EN: CIENCIAS ZOOTECNIA','grado_id'=>'1','id'=>'511'],
            ['nombre'=>'BACHILLER EN: CIENCIAS ZOOTECNIA','grado_id'=>'1','id'=>'512'],
            ['nombre'=>'BACHILLER EN: CIENCIAS DE LA COMUNICACIÓN','grado_id'=>'1','id'=>'790'],
            ['nombre'=>'BACHILLER EN: CIENCIAS ADMINISTRATIVAS','grado_id'=>'1','id'=>'791'],
            ['nombre'=>'BACHILLER EN: CIENCIAS CONTABLES','grado_id'=>'1','id'=>'792'],
            ['nombre'=>'BACHILLER EN: CIENCIAS ECONÓMICAS','grado_id'=>'1','id'=>'793'],
            ['nombre'=>'BACHILLER EN: CIENCIAS ADMINISTRATIVAS','grado_id'=>'1','id'=>'801'],
            ['nombre'=>'BACHILLER EN: ENFERMERÍA','grado_id'=>'1','id'=>'901'],
            ['nombre'=>'BACHILLER EN: ENFERMERÍA','grado_id'=>'1','id'=>'902'],
            ['nombre'=>'BACHILLER EN: ENFERMERÍA','grado_id'=>'1','id'=>'903'],
            ['nombre'=>'BACHILLER EN: ENFERMERÍA','grado_id'=>'1','id'=>'904'],
            ['nombre'=>'BACHILLER EN: ENFERMERÍA','grado_id'=>'1','id'=>'905'],
            ['nombre'=>'BACHILLER EN: ENFERMERÍA','grado_id'=>'1','id'=>'906'],
            ['nombre'=>'BACHILLER EN: DERECHO','grado_id'=>'1','id'=>'1000'],
            ['nombre'=>'BACHILLER EN: CIENCIAS INGENERIA DE MINAS','grado_id'=>'1','id'=>'1100'],

        
            // pregrado titulo
            ['nombre'=>'LICENCIADO(A)EN EDUCACIÓN','grado_id'=>'2','id'=>'601'],
            ['nombre'=>'LICENCIADO(A)EN EDUCACIÓN','grado_id'=>'2','id'=>'602'],
            ['nombre'=>'LICENCIADO(A)EN EDUCACIÓN','grado_id'=>'2','id'=>'603'],
            ['nombre'=>'LICENCIADO(A)EN EDUCACIÓN','grado_id'=>'2','id'=>'604'],
            ['nombre'=>'LICENCIADO(A)EN EDUCACIÓN','grado_id'=>'2','id'=>'605'],
            ['nombre'=>'LICENCIADO(A)EN EDUCACIÓN','grado_id'=>'2','id'=>'606'],
            ['nombre'=>'LICENCIADO(A)EN EDUCACIÓN','grado_id'=>'2','id'=>'607'],
            ['nombre'=>'LICENCIADO(A)EN EDUCACIÓN','grado_id'=>'2','id'=>'608'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: BIOLOGÍA Y QUÍMICA','grado_id'=>'2','id'=>'609'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: COMUNICACIÓN Y LITERATURA','grado_id'=>'2','id'=>'610'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: BIOLOGÍA Y QUÍMICA','grado_id'=>'2','id'=>'611'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: BIOLOGÍA Y QUÍMICA','grado_id'=>'2','id'=>'612'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: TECNOLOGÍA INFORMÁTICA Y TELECOMUNICACIONES','grado_id'=>'2','id'=>'613'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: TECNOLOGÍA INFORMÁTICA Y TELECOMUNICACIONES','grado_id'=>'2','id'=>'614'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: TECNOLOGÍA INFORMÁTICA Y TELECOMUNICACIONES','grado_id'=>'2','id'=>'615'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: CIENCIAS SOCIALES, FILOSOFÍA Y PSICOLOGÍA EDUCATIVA','grado_id'=>'2','id'=>'616'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN:MATEMÁTICA-FÍSICA','grado_id'=>'2','id'=>'617'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN:MATEMÁTICA-FÍSICA','grado_id'=>'2','id'=>'618'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: HISTORIA, CIENCIAS SOCIALES Y TURISMO','grado_id'=>'2','id'=>'619'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: HISTORIA, CIENCIAS SOCIALES Y TURISMO','grado_id'=>'2','id'=>'620'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: COMUNICACIÓN Y LITERATURA','grado_id'=>'2','id'=>'621'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: COMUNICACIÓN Y LITERATURA','grado_id'=>'2','id'=>'622'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: HISTORIA, CIENCIAS SOCIALES Y TURISMO','grado_id'=>'2','id'=>'623'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: HISTORIA, CIENCIAS SOCIALES Y TURISMO','grado_id'=>'2','id'=>'624'],
            ['nombre'=>'ABOGADO','grado_id'=>'2','id'=>'625'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN:MATEMÁTICA-FÍSICA','grado_id'=>'2','id'=>'626'],
            ['nombre'=>'LICENCIADO(A)EN EDUCACIÓN INICIAL','grado_id'=>'2','id'=>'627'],
            ['nombre'=>'LICENCIADO(A)EN EDUCACIÓN PRIMARIA','grado_id'=>'2','id'=>'628'],
            ['nombre'=>'LICENCIADO(A)EN EDUCACIÓN SEGUNDARIA','grado_id'=>'2','id'=>'629'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: BIOLOGÍA Y QUÍMICA','grado_id'=>'2','id'=>'630'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: COMUNICACIÓN Y LITERATURA','grado_id'=>'2','id'=>'631'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: TECNOLOGÍA INFORMÁTICA Y TELECOMUNICACIONES','grado_id'=>'2','id'=>'632'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: TECNOLOGÍA INFORMÁTICA Y TELECOMUNICACIONES','grado_id'=>'2','id'=>'633'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN:MATEMÁTICA-FÍSICA','grado_id'=>'2','id'=>'634'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: CIENCIAS SOCIALES, FILOSOFÍA Y PSICOLOGÍA EDUCATIVA','grado_id'=>'2','id'=>'635'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: HISTORIA, CIENCIAS SOCIALES Y TURISMO','grado_id'=>'2','id'=>'636'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: HISTORIA, CIENCIAS SOCIALES Y TURISMO','grado_id'=>'2','id'=>'637'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: LENGUAS EXTRANJERAS:INGLÉS-FRANCÉS','grado_id'=>'2','id'=>'638'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: LENGUAS EXTRANJERAS:INGLÉS-FRANCÉS','grado_id'=>'2','id'=>'639'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: COMUNICACIÓN Y LITERATURA','grado_id'=>'2','id'=>'640'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: COMUNICACIÓN Y LITERATURA','grado_id'=>'2','id'=>'641'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: COMUNICACIÓN Y LITERATURA','grado_id'=>'2','id'=>'642'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: COMUNICACIÓN Y LITERATURA','grado_id'=>'2','id'=>'643'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: TECNOLOGÍA INFORMÁTICA Y TELECOMUNICACIONES','grado_id'=>'2','id'=>'644'],
            ['nombre'=>'LICENCIADO(A)EN EDUCACIÓN PRIMARIA','grado_id'=>'2','id'=>'645'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: TECNOLOGÍA INFORMÁTICA Y TELECOMUNICACIONES','grado_id'=>'2','id'=>'646'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: BIOLOGÍA Y QUÍMICA','grado_id'=>'2','id'=>'647'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: TECNOLOGÍA INFORMÁTICA Y TELECOMUNICACIONES','grado_id'=>'2','id'=>'648'],
            ['nombre'=>'LICENCIADO(A)EN EDUCACIÓN INICIAL','grado_id'=>'2','id'=>'649'],
            ['nombre'=>'LICENCIADO(A)EN EDUCACIÓN PRIMARIA','grado_id'=>'2','id'=>'650'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN:MATEMÁTICA-FÍSICA','grado_id'=>'2','id'=>'651'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: HISTORIA, CIENCIAS SOCIALES Y TURISMO','grado_id'=>'2','id'=>'652'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: HISTORIA, CIENCIAS SOCIALES Y TURISMO','grado_id'=>'2','id'=>'653'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: LENGUAS :INGLÉS-QUECHUA','grado_id'=>'2','id'=>'654'], 
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN INICIAL PRIMARIA','grado_id'=>'2','id'=>'655'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: COMUNICACIÓN Y LITERATURA','grado_id'=>'2','id'=>'656'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: MUSICA Y ARTE','grado_id'=>'2','id'=>'657'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: RELIGION Y CIENCIAS SOCIALES','grado_id'=>'2','id'=>'658'],
            ['nombre'=>'LICENCIADO(A)EN EDUCACIÓN INICIAL','grado_id'=>'2','id'=>'659'],
            ['nombre'=>'LICENCIADO(A)EN EDUCACIÓN PRIMARIA','grado_id'=>'2','id'=>'660'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: TECNOLOGÍA INFORMÁTICA Y TELECOMUNICACIONES','grado_id'=>'2','id'=>'661'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: BIOLOGÍA Y QUÍMICA','grado_id'=>'2','id'=>'662'],
            ['nombre'=>'LICENCIADO(A)EN EDUCACIÓN INICIAL','grado_id'=>'2','id'=>'663'],
            ['nombre'=>'LICENCIADO(A)EN EDUCACIÓN PRIMARIA','grado_id'=>'2','id'=>'664'],
            ['nombre'=>'LICENCIADO(A)EN EDUCACIÓN INICIAL Y PRIMARIA','grado_id'=>'2','id'=>'665'],
            ['nombre'=>'LICENCIADO(A) EN EDUCACIÓN CON MENCIÓN: COMUNICACIÓN Y LITERATURA','grado_id'=>'2','id'=>'666'],
            ['nombre'=>'LICENCIADO(A)EN EDUCACIÓN PRIMARIA','grado_id'=>'2','id'=>'667'],
            ['nombre'=>'MÉDICO CIRUJANO','grado_id'=>'2','id'=>'201'],
            ['nombre'=>'INGENIERO AMBIENTAL','grado_id'=>'2','id'=>'341'],
            ['nombre'=>'INGENIERO AMBIENTAL','grado_id'=>'2','id'=>'342'],
            ['nombre'=>'INGENIERO CIVIL','grado_id'=>'2','id'=>'343'],
            ['nombre'=>'INGENIERO GEÓLOGO','grado_id'=>'2','id'=>'344'],
            ['nombre'=>'INGENIERO METALURGÍSTA','grado_id'=>'2','id'=>'345'],
            ['nombre'=>'INGENIERO DE MINAS','grado_id'=>'2','id'=>'346'],
            ['nombre'=>'INGENIERO DE SISTEMAS Y COMPUTACIÓN','grado_id'=>'2','id'=>'347'],
            ['nombre'=>'INGENIERO DE SISTEMAS Y COMPUTACIÓN','grado_id'=>'2','id'=>'348'],
            ['nombre'=>'CIRUJANO DENTISTA','grado_id'=>'2','id'=>'401'],
            ['nombre'=>'INGENIERO AGRÓNOMO','grado_id'=>'2','id'=>'551'],
            ['nombre'=>'INGENIERO AGRÓNOMO','grado_id'=>'2','id'=>'552'],
            ['nombre'=>'INGENIERO AGRÓNOMO','grado_id'=>'2','id'=>'553'],
            ['nombre'=>'INGENIERO AGRÓNOMO','grado_id'=>'2','id'=>'554'],
            ['nombre'=>'INGENIERO AGRÓNOMO','grado_id'=>'2','id'=>'555'],
            ['nombre'=>'INGENIERO AGRÓNOMO','grado_id'=>'2','id'=>'556'],
            ['nombre'=>'INGENIERO AGRÓNOMO','grado_id'=>'2','id'=>'557'],
            ['nombre'=>'INGENIERO EN INDUSTRIAS ALIMENTARIAS','grado_id'=>'2','id'=>'558'],
            ['nombre'=>'INGENIERO EN INDUSTRIAS ALIMENTARIAS','grado_id'=>'2','id'=>'559'],
            ['nombre'=>'INGENIERO ZOOTECNISTA','grado_id'=>'2','id'=>'560'],
            ['nombre'=>'INGENIERO ZOOTECNISTA','grado_id'=>'2','id'=>'561'],
            ['nombre'=>'INGENIERO ZOOTECNISTA','grado_id'=>'2','id'=>'562'],
            ['nombre'=>'LICENCIADO EN CIENCIAS DE LA COMUNICACIÓN','grado_id'=>'2','id'=>'700'],
            ['nombre'=>'LICENCIADO(A) EN ADMINISTRACIÓN','grado_id'=>'2','id'=>'701'],
            ['nombre'=>'CONTADOR PÚBLICO','grado_id'=>'2','id'=>'702'],
            ['nombre'=>'ECONOMISTA','grado_id'=>'2','id'=>'703'],
            ['nombre'=>'LICENCIADO(A) EN ADMINISTRACIÓN','grado_id'=>'2','id'=>'800'],
            ['nombre'=>'LICENCIADA (O) EN ENFERMERÍA','grado_id'=>'2','id'=>'990'],
            ['nombre'=>'LICENCIADA (O) EN ENFERMERÍA','grado_id'=>'2','id'=>'992'],
            ['nombre'=>'LICENCIADA (O) EN ENFERMERÍA','grado_id'=>'2','id'=>'993'],
            ['nombre'=>'LICENCIADA (O) EN ENFERMERÍA','grado_id'=>'2','id'=>'994'],
            ['nombre'=>'OBSTETRA','grado_id'=>'2','id'=>'995'],
            ['nombre'=>'OBSTETRA','grado_id'=>'2','id'=>'996'],
            ['nombre'=>'ABOGADO','grado_id'=>'2','id'=>'1001'],
            ['nombre'=>'INGENIERO DE MINAS','grado_id'=>'2','id'=>'1101'],

        

        // posgrado
            ['nombre'=>'MAESTRO EN: LIDERAZGO Y GESTIÓN EDUCATIVA','grado_id'=>'3','id'=>'29'],
            ['nombre'=>'MAESTRO EN: GESTIÓN DEL SISTEMA AMBIENTAL','grado_id'=>'3','id'=>'30'],
            ['nombre'=>'MAESTRO EN: SALUD PÚBLICA Y COMUNITARIA, MENCIÓN: GERENCIA DE SALUD','grado_id'=>'3','id'=>'31'],
            ['nombre'=>'MAESTRO EN: DOCENCIA EN EL NIVEL SUPERIOR','grado_id'=>'3','id'=>'32'],
            ['nombre'=>'MAESTRO EN: GESTIÓN EMPRESARIAL','grado_id'=>'3','id'=>'33'],
            ['nombre'=>'MAESTRO EN: PLANIFICACIÓN Y PROYECTOS DE DESARROLLO','grado_id'=>'3','id'=>'34'],
            ['nombre'=>'MAESTRO EN: ODONTOLOGÍA','grado_id'=>'3','id'=>'35'],
            ['nombre'=>'MAESTRO EN: CIENCIAS CONTABLES MENCIÓN: AUDITORÍA INTEGRAL','grado_id'=>'3','id'=>'36'],
            ['nombre'=>'MAESTRO EN: CIENCIAS DE LA ADMINISTRACIÓN, CON MENCIÓN EN GESTIÓN PÚBLICA Y DESARROLLO LOCAL','grado_id'=>'3','id'=>'37'],
            ['nombre'=>'MAESTRO EN: GERENCIA E INNOVACIÓN EDUCATIVA','grado_id'=>'3','id'=>'38'],
            ['nombre'=>'MAESTRO EN: DIDÁCTICA Y TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN','grado_id'=>'3','id'=>'39'],
            ['nombre'=>'MAESTRO EN: DERECHO DEL TRABAJO Y SEGURIDAD SOCIAL','grado_id'=>'3','id'=>'40'],
            ['nombre'=>'MAESTRO EN: DERECHO PENAL Y PROCESAL PENAL','grado_id'=>'3','id'=>'41'],
            ['nombre'=>'MAESTRO EN: DERECHO AMBIENTAL','grado_id'=>'3','id'=>'42'],
            ['nombre'=>'MAESTRO EN: DERECHO CIVIL Y COMERCIAL','grado_id'=>'3','id'=>'43'],
            ['nombre'=>'MAESTRO EN: CIENCIAS DE LA COMUNICACIÓN MENCIÓN :RELACIONES COMUNITARIAS Y RESOLUCIÓN DE CONFLICTOS SOCIALES','grado_id'=>'3','id'=>'44'],
            ['nombre'=>'MAESTRO EN: CIENCIAS - MENCIÓN: SEGURIDAD Y SALUD OCUPACIONAL MINERA','grado_id'=>'3','id'=>'45'],
            ['nombre'=>'DOCTORADO EN: CIENCIAS DE LA EDUCACIÓN','grado_id'=>'4','id'=>'46'],
            ['nombre'=>'DOCTORADO EN: ADMINISTRACIÓN','grado_id'=>'4','id'=>'47'],
            

        ];
        DB::table('denominaciones')->insert($denominacion);
    }
    }

